name: CI
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Run ESLint
        run: $(npm bin)/eslint .
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - run: npm install
      - run: npm install why-is-node-running
      - name: Run tests
        run: |
          MONGODB_TEST='127.0.0.1:27017/mocha_test' $(npm bin)/mocha */*.spec.js
          ps
          ps aux
