name: CI
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: eslint .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - run: npm install
      - name: Run tests
        run: npm run test
